/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import alaposztalyok.Adat;
import alaposztalyok.FajlKezelo;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import vezerlo.AdatFrame;

/**
 *
 * @author Sandor
 */
public class AdatPanel extends javax.swing.JPanel {

    private AdatFrame parentFrame;
    private Adat adat;

    public AdatPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leltarLbl = new javax.swing.JLabel();
        lKLbl = new javax.swing.JLabel();
        eszkozLbl = new javax.swing.JLabel();
        gyartoLbl = new javax.swing.JLabel();
        tipusLbl = new javax.swing.JLabel();
        gySzLbl = new javax.swing.JLabel();
        felhasznLbl = new javax.swing.JLabel();
        osztalyLbl = new javax.swing.JLabel();
        epuletLbl = new javax.swing.JLabel();
        szobaLbl = new javax.swing.JLabel();
        statuszLbl = new javax.swing.JLabel();
        gySzTextField = new javax.swing.JTextField();
        gyartoTextField = new javax.swing.JTextField();
        szobaTextField = new javax.swing.JTextField();
        felhasznTextField = new javax.swing.JTextField();
        tipusTextField = new javax.swing.JTextField();
        eszkozCmbBox = new javax.swing.JComboBox();
        osztalyCmbBox = new javax.swing.JComboBox();
        epuletCmbBox = new javax.swing.JComboBox();
        statusCmbBox = new javax.swing.JComboBox();
        rogzitBtn = new javax.swing.JButton();
        visszalepBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 500));

        leltarLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        leltarLbl.setText("Adatok");

        lKLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lKLbl.setText("Leltári kód:");

        eszkozLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        eszkozLbl.setText("Eszköz:");

        gyartoLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        gyartoLbl.setText("Gyártó:");

        tipusLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tipusLbl.setText("Típus:");

        gySzLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        gySzLbl.setText("Gyári szám:");

        felhasznLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        felhasznLbl.setText("Felhasználó:");

        osztalyLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        osztalyLbl.setText("Osztály:");

        epuletLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        epuletLbl.setText("Épület:");

        szobaLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        szobaLbl.setText("Szoba:");

        statuszLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        statuszLbl.setText("Státusz:");

        gySzTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        gyartoTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        szobaTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        felhasznTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        tipusTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        eszkozCmbBox.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        eszkozCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Válasszon", "Monitor", "PC", "Notebook" }));

        osztalyCmbBox.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        osztalyCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Válasszon", "Informatika", "Pénzügy", "HR" }));

        epuletCmbBox.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        epuletCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Válasszon", "T1 Terminal", "T2 Terminal", "SkyCourt" }));

        statusCmbBox.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        statusCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Válasszon", "Aktív", "Inaktív", "Selejt" }));

        rogzitBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        rogzitBtn.setText("Mentés");
        rogzitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rogzitBtnActionPerformed(evt);
            }
        });

        visszalepBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        visszalepBtn.setText("Visszalép");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(rogzitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(visszalepBtn)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tipusLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lKLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                        .addComponent(gyartoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                        .addComponent(eszkozLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(gySzLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eszkozCmbBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gyartoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addComponent(gySzTextField)
                                .addComponent(tipusTextField)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(osztalyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(osztalyCmbBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(epuletLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(szobaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statuszLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusCmbBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(epuletCmbBox, 0, 115, Short.MAX_VALUE)
                                    .addComponent(szobaTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(felhasznLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(felhasznTextField)))))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(leltarLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leltarLbl)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lKLbl)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eszkozLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eszkozCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gyartoLbl)
                            .addComponent(gyartoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipusLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(osztalyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(osztalyCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(epuletLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(epuletCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(szobaLbl)
                            .addComponent(szobaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statuszLbl)
                            .addComponent(statusCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gySzLbl)
                        .addComponent(gySzTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(felhasznLbl)
                        .addComponent(felhasznTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rogzitBtn)
                    .addComponent(visszalepBtn))
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rogzitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rogzitBtnActionPerformed
        try {
            mentes();
        } catch (IOException ex) {
            Logger.getLogger(AdatPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rogzitBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox epuletCmbBox;
    private javax.swing.JLabel epuletLbl;
    private javax.swing.JComboBox eszkozCmbBox;
    private javax.swing.JLabel eszkozLbl;
    private javax.swing.JLabel felhasznLbl;
    private javax.swing.JTextField felhasznTextField;
    private javax.swing.JLabel gySzLbl;
    private javax.swing.JTextField gySzTextField;
    private javax.swing.JLabel gyartoLbl;
    private javax.swing.JTextField gyartoTextField;
    private javax.swing.JLabel lKLbl;
    private javax.swing.JLabel leltarLbl;
    private javax.swing.JComboBox osztalyCmbBox;
    private javax.swing.JLabel osztalyLbl;
    private javax.swing.JButton rogzitBtn;
    private javax.swing.JComboBox statusCmbBox;
    private javax.swing.JLabel statuszLbl;
    private javax.swing.JLabel szobaLbl;
    private javax.swing.JTextField szobaTextField;
    private javax.swing.JLabel tipusLbl;
    private javax.swing.JTextField tipusTextField;
    private javax.swing.JButton visszalepBtn;
    // End of variables declaration//GEN-END:variables

    public void setAdatFrame(AdatFrame frame) {
        parentFrame = frame;
    }

    public void ujAdatBevitel() {

    }

    public void init(Adat adat) {
        this.adat = adat;
        lKLbl.setText("Leltári Kód: " + String.valueOf(adat.getLeltariKod()));
        eszkozCmbBox.setSelectedItem(adat.getEszkoz());
        gyartoTextField.setText(adat.getGyarto());
        tipusTextField.setText(adat.getTipus());
        gySzTextField.setText(adat.getGyariSzam());
        osztalyCmbBox.setSelectedItem(adat.getOsztaly());
        epuletCmbBox.setSelectedItem(adat.getEpulet());
        szobaTextField.setText(adat.getSzoba());
        statusCmbBox.setSelectedItem(adat.getStatus());
        felhasznTextField.setText(adat.getFelhasznalo());
    }

    private void mentes() throws IOException {
        adat.setLeltariKod(adat.getLeltariKod());
        adat.setEszkoz((String) eszkozCmbBox.getSelectedItem());
        adat.setGyarto(gyartoTextField.getText());
        adat.setTipus(tipusTextField.getText());
        adat.setGyariSzam(gySzTextField.getText());
        adat.setOsztaly((String) osztalyCmbBox.getSelectedItem());
        adat.setEpulet((String) epuletCmbBox.getSelectedItem());
        adat.setSzoba(szobaTextField.getText());
        adat.setStatus((String) statusCmbBox.getSelectedItem());
        adat.setFelhasznalo(felhasznTextField.getText());
        adat.setAdatKezelo(LoginPanel.felhasznalonev);
        adat.setDatum(new Date());
        FajlKezelo.adatModosit(adat);

    }

}
