/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import alaposztalyok.Adat;
import alaposztalyok.FajlKezelo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultListModel;
import rendezoosztaly.DatumSzerint;
import rendezoosztaly.FelhasznaloSzerint;
import vezerlo.AdatFrame;
import vezerlo.MainFrame;

/**
 *
 * @author Sandor
 */
public class MainPanel extends javax.swing.JPanel {

    private DefaultListModel<Adat> adatLstModel = new DefaultListModel<>();
    private List<Adat> rendezolista = new ArrayList<>(FajlKezelo.adatLeker());
    public static MainFrame parentFrame;

    public MainPanel() {
        initComponents();
        modellBetoltes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leltarLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainLst = new javax.swing.JList();
        adatModositoLbl = new javax.swing.JLabel();
        ujAdatBtn = new javax.swing.JButton();
        adatModositoBtn = new javax.swing.JButton();
        adatTorloBtn = new javax.swing.JButton();
        kilepoBtn = new javax.swing.JButton();
        adatModositoLbl1 = new javax.swing.JLabel();
        szuresCmbBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        szuroLst = new javax.swing.JList();
        szurBtn = new javax.swing.JButton();
        keresesLbl = new javax.swing.JLabel();
        keresesLbl1 = new javax.swing.JLabel();
        keresoTextField = new javax.swing.JTextField();
        rendezBtn = new javax.swing.JButton();
        rendezesCmbBox = new javax.swing.JComboBox();
        keresBtn = new javax.swing.JButton();
        helyreallitBtn = new javax.swing.JButton();
        keresesCmbBox = new javax.swing.JComboBox();

        setPreferredSize(new java.awt.Dimension(1000, 650));

        leltarLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        leltarLbl.setText("Leltár");

        mainLst.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        mainLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(mainLst);

        adatModositoLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        adatModositoLbl.setText("Adatmódosító műveletek");

        ujAdatBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ujAdatBtn.setText("Új eszköz felvétele");
        ujAdatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujAdatBtnActionPerformed(evt);
            }
        });

        adatModositoBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        adatModositoBtn.setText("Eszköz módosítása");

        adatTorloBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        adatTorloBtn.setText("Eszköz törlése");

        kilepoBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        kilepoBtn.setText("Kilépés");
        kilepoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilepoBtnActionPerformed(evt);
            }
        });

        adatModositoLbl1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        adatModositoLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adatModositoLbl1.setText("Adatszűrés");

        szuresCmbBox.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        szuresCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Válasszon", "Eszköz", "Osztály", "Épület", "Státusz" }));
        szuresCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szuresCmbBoxActionPerformed(evt);
            }
        });

        szuroLst.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        szuroLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(szuroLst);

        szurBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        szurBtn.setText("Szűr!");

        keresesLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        keresesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keresesLbl.setText("Keresés");

        keresesLbl1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        keresesLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keresesLbl1.setText("Rendezés");

        keresoTextField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        keresoTextField.setToolTipText("");

        rendezBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        rendezBtn.setText("Rendez!");
        rendezBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendezBtnActionPerformed(evt);
            }
        });

        rendezesCmbBox.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        rendezesCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Válasszon", "Név", "Dátum" }));

        keresBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        keresBtn.setText("Keres!");
        keresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keresBtnActionPerformed(evt);
            }
        });

        helyreallitBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        helyreallitBtn.setText("Helyreállít!");
        helyreallitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helyreallitBtnActionPerformed(evt);
            }
        });

        keresesCmbBox.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        keresesCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Válasszon", "Felhasználó", "Dátum", "Gyári szám", "Leltári kód", "Adatkezelő" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(leltarLbl)
                                .addGap(391, 391, 391)
                                .addComponent(kilepoBtn))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adatModositoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ujAdatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adatModositoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adatTorloBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(szuresCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(szurBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(keresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(keresoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(keresesCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(adatModositoLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(keresesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(keresesLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rendezesCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rendezBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(helyreallitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leltarLbl)
                    .addComponent(kilepoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adatModositoLbl)
                    .addComponent(adatModositoLbl1)
                    .addComponent(keresesLbl)
                    .addComponent(keresesLbl1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(szuresCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ujAdatBtn))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(adatModositoBtn)
                                    .addComponent(szurBtn))
                                .addGap(28, 28, 28)
                                .addComponent(adatTorloBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rendezesCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(keresesCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(keresoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rendezBtn)
                                    .addComponent(keresBtn))))
                        .addGap(20, 20, 20)
                        .addComponent(helyreallitBtn)
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ujAdatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujAdatBtnActionPerformed
        ujAdatBevitel();
    }//GEN-LAST:event_ujAdatBtnActionPerformed

    private void kilepoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilepoBtnActionPerformed
        kilepes();
    }//GEN-LAST:event_kilepoBtnActionPerformed

    private void rendezBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendezBtnActionPerformed
        if (rendezesCmbBox.getSelectedIndex() == 1) {
            felhasznaloSzerintRendez();
        }
        if (rendezesCmbBox.getSelectedIndex() == 2) {
            datumSzerintRendez();
        }
    }//GEN-LAST:event_rendezBtnActionPerformed

    private void helyreallitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helyreallitBtnActionPerformed
        helyreallit();
        modellBetoltes();
    }//GEN-LAST:event_helyreallitBtnActionPerformed

    private void keresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keresBtnActionPerformed
        if (keresesCmbBox.getSelectedIndex() == 1) {
            felhasznaloSzerintKeres();
        }
        if (keresesCmbBox.getSelectedIndex() == 2) {
            datumSzerintKeres();
        }
        if (keresesCmbBox.getSelectedIndex() == 3) {
            gyariSzamSzerintKeres();
        }
        if (keresesCmbBox.getSelectedIndex() == 4) {
            leltarikodSzerintKeres();
        }
        if (keresesCmbBox.getSelectedIndex() == 5) {
            adatkezeloSzerintKeres();
        }
    }//GEN-LAST:event_keresBtnActionPerformed

    private void szuresCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szuresCmbBoxActionPerformed
        if (szuresCmbBox.getSelectedIndex() == 1) {
            szuroLst.setModel(new javax.swing.AbstractListModel() {
                String[] strings = {"Monitor", "PC", "Notebook"};

                public int getSize() {
                    return strings.length;
                }

                public Object getElementAt(int i) {
                    return strings[i];
                }
            });
        }
    }//GEN-LAST:event_szuresCmbBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adatModositoBtn;
    private javax.swing.JLabel adatModositoLbl;
    private javax.swing.JLabel adatModositoLbl1;
    private javax.swing.JButton adatTorloBtn;
    private javax.swing.JButton helyreallitBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keresBtn;
    private javax.swing.JComboBox keresesCmbBox;
    private javax.swing.JLabel keresesLbl;
    private javax.swing.JLabel keresesLbl1;
    private javax.swing.JTextField keresoTextField;
    private javax.swing.JButton kilepoBtn;
    private javax.swing.JLabel leltarLbl;
    private javax.swing.JList mainLst;
    private javax.swing.JButton rendezBtn;
    private javax.swing.JComboBox rendezesCmbBox;
    private javax.swing.JButton szurBtn;
    private javax.swing.JComboBox szuresCmbBox;
    private javax.swing.JList szuroLst;
    private javax.swing.JButton ujAdatBtn;
    // End of variables declaration//GEN-END:variables

    public static void setMainFrame(MainFrame frame) {
        parentFrame = frame;
    }

// modellBetoltes() adatLstModel-be berakja az adatokat.
    private void modellBetoltes() {
        adatLstModel.clear();
        mainLst.setModel(adatLstModel);
        List<Adat> feltoltoLista = new ArrayList<>(FajlKezelo.adatLeker());
        for (Adat adat : feltoltoLista) {
            adatLstModel.addElement(adat);
        }
    }

    private void ujAdatBevitel() {
        new vezerlo.AdatFrame();
    }

// Kilépő metódus
    private void kilepes() {
        parentFrame.setVisible(false);
        parentFrame.dispose();
    }

// Rendező metódusok
    private void felhasznaloSzerintRendez() {
        Collections.sort(rendezolista, new FelhasznaloSzerint());
        adatLstModel.clear();
        for (Adat adat : rendezolista) {
            adatLstModel.addElement(adat);
        }
    }

    private void datumSzerintRendez() {
        Collections.sort(rendezolista, new DatumSzerint());
        adatLstModel.clear();
        for (Adat adat : rendezolista) {
            adatLstModel.addElement(adat);
        }
    }

// Kereso metodusok
    private void felhasznaloSzerintKeres() {
        adatLstModel.clear();
        for (Adat adat : rendezolista) {
            if (keresoTextField.getText().equals(adat.getFelhasznalo())) {
                adatLstModel.addElement(adat);
            }
        }
    }

    private void datumSzerintKeres() {
        adatLstModel.clear();
        for (Adat adat : rendezolista) {
            if (keresoTextField.getText().equals(adat.getDatum())) {
                adatLstModel.addElement(adat);
            }
        }
    }

    private void gyariSzamSzerintKeres() {
        adatLstModel.clear();
        for (Adat adat : rendezolista) {
            if (keresoTextField.getText().equals(adat.getGyariSzam())) {
                adatLstModel.addElement(adat);
            }
        }
    }

    private void leltarikodSzerintKeres() {
        adatLstModel.clear();
        for (Adat adat : rendezolista) {
            if (keresoTextField.getText().equals(String.valueOf(adat.getLeltariKod()))) {
                adatLstModel.addElement(adat);
            }
        }
    }

    private void adatkezeloSzerintKeres() {
        adatLstModel.clear();
        for (Adat adat : rendezolista) {
            if (keresoTextField.getText().equals(adat.getAdatKezelo())) {
                adatLstModel.addElement(adat);
            }
        }
    }

    private void helyreallit() {
        szuresCmbBox.setSelectedIndex(0);
        szuroLst.clearSelection();
        // TODO: szuro lista modellt torolni kell.
        keresesCmbBox.setSelectedIndex(0);
        keresoTextField.setText(null);
        rendezesCmbBox.setSelectedIndex(0);
    }
}
